<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>TheNetTunnel</Title>
    <PackageId>TheNetTunnel</PackageId>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<Version>1.0.12</Version>
  </PropertyGroup>
	<ItemGroup>
		<Content Include="..\..\README.md">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\..\LICENSE">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.16" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

</Project>
