<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>    
    <TargetFramework>net6.0</TargetFramework>    
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TheNetTunnel\TheNetTunnel.csproj" />
    <ProjectReference Include="..\CommonTestTools\CommonTestTools.csproj" />
    <ProjectReference Include="..\TNT.SpeedTest\TNT.SpeedTest.csproj" />
  </ItemGroup>
  
</Project>
